### ISSUE TITLE
Simple filtering on vocabulary id

### ISSUE THREAD

**Issue by Sigfried** [Sigfried/vocab-pop#15]
Can just be a config setting or something...I'll filter out vocabs Melanie wants filtered out.

**Comment by MelaniePhilofsky** [comment]
I would like the following code systems included: SNOMED, ICD9CM, CPT4, HCPCS, LOINC, RXNORM, NDC, GPI, UCUM, GENDER, RACE, PLACE OF SERVICE MEDDRA, INDICATION, ICD10PCS, DRG, MDC, APC, REVENUSE CODE, ETHNICITY, NUCC, SPECIALTY, PCORNET, ICD10CM, ABMS

**Comment by Sigfried** [comment]
This is done. No UI, but a hard-coded list, so only these are included...at least in focal concepts. For related concepts there's no filter yet, but will be soon.
